databases:
  - name: alm_db
    databaseName: alm_db
    user: alm_user
    plan: free

services:
  - type: web
    name: alm-voting
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn e_voting.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alm_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: e_voting.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true