services:
  - type: web
    name: online-voting-system
    env: python
    buildCommand: |
      python -m pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn e_voting.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "alm-online-voting-system.onrender.com,127.0.0.1,localhost"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
      - key: USE_X_FORWARDED_HOST
        value: "True"
      - key: USE_X_FORWARDED_PORT
        value: "True"
      - key: TIDB_DB_NAME
        value: test
      - key: TIDB_DB_USER
        value: 3qQmvWwgcRatJ3q.root
      - key: TIDB_DB_PASSWORD
        value: XfrrSTz4Uv9XwsjE
      - key: TIDB_DB_HOST
        value: gateway01.eu-central-1.prod.aws.tidbcloud.com
      - key: TIDB_DB_PORT
        value: "4000"
      - key: DATABASE_URL
        value: "mysql://user:password@host:port/database"
      - key: SECRET_KEY
        value: "your-secret-key-here"
    pythonPath: /opt/render/project/src
    rootDirectory: /opt/render/project/src
    buildImage:
      dockerfile: Dockerfile
      context: .
    autoDeploy: true