services:
  - type: web
    name: pos-system
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pos.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: pos.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 